# Site information
site_name: THOTH Documentation
site_url: https://sitename.example
site_author: Stelios Alvanos
site_description: THOTH Documentation

# Copyright
copyright: Copyright &copy; 2025 TEXTaiLES

# Repository
repo_name: thoth-documentation
repo_url: https://github.com/TEXTaiLES/thoth-documentation

# Config
theme:
  name: material
  palette:
    scheme: slate
    primary: white
  logo: assets/thoth-logo.png
  favicon: assets/thoth-logo.png

# Extra
extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/TEXTaiLES/thoth

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

# Page
nav:
  - Deployment:

    - Basic Installation        : deployment/installation_basic.md
    - Advanced Installation     : deployment/installation_advanced.md
    - Deploy with Docker        : deployment/docker.md

  - Scene:

    - Opening a scene with THOTH: scene/open_scene.md
    - Logging in                : scene/login.md
    - Collaborative             : scene/collab.md
    
  - User Manual:

    - User Interface   : manual/ui.md
    - Tools            : manual/tools.md
    - Layers           : manual/layers.md
    - Models           : manual/models.md
    - Metadata         : manual/metadata.md
    - History          : manual/history.md
    - Exporting changes: manual/export.md

  - Keybinds: keybinds/keybinds.md

  # - API:
  #   - Events: api/events.md
  #   - REST API: api/rest.md